### ISSUE TITLE
希望可以增加EPG节目单，已star

### ISSUE THREAD

**Issue by 239144498** [chenenpei/iptv#1]
希望可以增加EPG节目单，已star

**Comment by chenenpei** [comment]
感谢关注。

接下来会优先实现自主添加源的能力，然后提供 apk 包和 ipa 包。因为网页版受制于 CORS 限制，很多频道无法播放。

后续会支持其他格式源的添加。

**Comment by 239144498** [comment]
> 

太棒了，我好期待(★ ω ★)
